Поиск проблемы
Запуск команды:
docker-compose up --build

Приводит к ошибке:
 > [8/8] RUN env GOOS=linux go build main.go:
#17 0.312 no required module provides package main.go; to add it:
#17 0.312       go get main.go
------
executor failed running [/bin/sh -c env GOOS=linux go build main.go]: exit code: 1
ERROR: Service 'api' failed to build : Build failed